services:
  db:
    image: postgis/postgis:17-3.6-alpine
    platform: linux/amd64
    container_name: smarthome_db
    environment:
      POSTGRES_DB: smarthome_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5501:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smarthome_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarthome_backend
    command: python manage.py runserver 0.0.0.0:5500
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5500:5500"
    volumes:
      - .:/app

volumes:
  db_data:
